### ISSUE TITLE
機関誌「地図」最新号目次を更新する。（Vol.54 No.1 通巻213号）

### ISSUE THREAD

**Issue by TArahori** [japancartographersassociation/www_jcacj_org#4]
@mapconcierge @Kenyat1989 
機関誌「地図」最新号目次を更新する。（Vol.54 No.1 通巻213号）
更新ページ①　トップページメニュー→機関誌→最新号目次：目次ページ　http://jcacj.org/table.html
更新ページ②　トップページ→更新情報　http://jcacj.org/index.html
※上から論文のカテゴリー、タイトル、著者名の順に記載しています。

Vol.54 No.1 (通巻213号) 2016年
【巻頭言】 
地図年（IMY）に向けた日本地図学会の取り組み
若林芳樹
【資料】
投影図法に基づく鳥瞰図制作のあゆみ
織田雅己
　キーワード：鳥瞰図，投影図法，田山利三郎，今村巳之助
【資料・添付地図解説】
地図作品展ポスター2016　―地図の普及と子どもの成長を願って―
木立結花
　キーワード：地図作品展，手作り地図
【ICA・ICC】
第27回国際地図学会議・第16回国際地図学協会総会（ブラジル・リオデジャネイロ）参加報告
森田　喬・有川正俊・太田守重・伊藤香織・SI Ruochen・中埜貴元・若林芳樹・田中雅大・藤田秀之・
LU Min・久木元美琴
【第200回例会】
シンポジウム「観光立国に向けて，地図はどう貢献できるのか」　
遠藤宏之・片桐由希子・奥秋　圭・土橋文武・篠崎　透
【第201回例会】
草加市巡検と第6回会社見学：（株）渡辺教具製作所
LU Min・有川正俊
【書評・紹介】
マップス　新・世界図絵
佐藤　潤
【特別会員名簿】
【学会記事】
【添付地図】
地図作品展ポスター2016

**Comment by TArahori** [comment]
更新しました。
http://jcacj.org/table.html

**Comment by mapconcierge** [comment]
Thanks!! 👍

**Comment by mapconcierge** [comment]
閉じます！
